<a href="https://colab.research.google.com/github/pontessdaniel/Fiel-Logistica-PIL-2-Semestre/blob/main/Arquivos_Relacionados_FielLog.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [6]:
import numpy as np

In [7]:
caminho_in = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/'
caminho_out = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/'

In [8]:
from google.colab import drive
drive.mount('/content/drive')
df_2022= '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/EXP_2022.csv'
df_2023= '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/EXP_2023.csv'
df_2024= '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/EXP_2024.csv'

Mounted at /content/drive

In [9]:
df_2022 = caminho_in + 'EXP_2022.csv'

In [10]:
pd.read_csv(df_2022, low_memory=False, sep=';', encoding= 'UTF-8')

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2022,6,85045000,11,69,MG,4,817600,2,1399,19576
1,2022,4,39219019,10,586,SP,7,917500,3914,3914,12672
2,2022,1,44071100,16,249,SC,1,927800,21945,8409167,5177394
3,2022,11,84672100,11,521,RS,1,817800,10,25,487
4,2022,10,8072000,10,23,RN,4,417901,55356,55356,71511
...,...,...,...,...,...,...,...,...,...,...,...
1495863,2022,11,32061910,10,845,SP,7,1010252,975,975,5489
1495864,2022,1,12024200,10,434,AM,1,227600,4,4,26
1495865,2022,9,18040000,21,249,BA,1,517800,180,180000,1295568
1495866,2022,8,16010000,10,99,SC,1,927800,1820,1820,1930
1495867,2022,8,64031900,13,69,RJ,4,817700,1,1,68

In [11]:
df_2023 = caminho_in + 'EXP_2023.csv'
with open(df_2023, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

Linha 1: "CO_ANO";"CO_MES";"CO_NCM";"CO_UNID";"CO_PAIS";"SG_UF_NCM";"CO_VIA";"CO_URF";"QT_ESTAT";"KG_LIQUIDO";"VL_FOB"

Linha 2: "2023";"03";"84139190";"10";"160";"RJ";"04";"0817700";107365;5;20

Linha 3: "2023";"12";"73182100";"10";"764";"SP";"01";"0817800";0;0;84

Linha 4: "2023";"04";"84219999";"10";"040";"RS";"04";"0817600";2;2;758

Linha 5: "2023";"05";"85291090";"10";"063";"RJ";"07";"1017503";1;1;275

In [12]:
pd.read_csv(df_2023, low_memory=False, sep=';', encoding= 'UTF-8')

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2023,3,84139190,10,160,RJ,4,817700,107365,5,20
1,2023,12,73182100,10,764,SP,1,817800,0,0,84
2,2023,4,84219999,10,40,RS,4,817600,2,2,758
3,2023,5,85291090,10,63,RJ,7,1017503,1,1,275
4,2023,10,84825010,11,63,MG,7,1017503,2,0,9
...,...,...,...,...,...,...,...,...,...,...,...
1563654,2023,11,64029990,13,337,RS,1,817800,4284,2549,38719
1563655,2023,11,85321000,11,670,RS,4,1017801,24,13,226
1563656,2023,2,20091900,10,586,PR,7,917500,17175,17175,12457
1563657,2023,12,9101100,10,160,MA,1,317903,10,10,30
1563658,2023,5,42029200,11,249,RS,4,817700,2,6,30

In [13]:
df_2024 = caminho_in + 'EXP_2024.csv'
with open(df_2024, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

Linha 1: "CO_ANO";"CO_MES";"CO_NCM";"CO_UNID";"CO_PAIS";"SG_UF_NCM";"CO_VIA";"CO_URF";"QT_ESTAT";"KG_LIQUIDO";"VL_FOB"

Linha 2: "2024";"04";"94036000";"11";"245";"SP";"04";"0817600";8;425;20423

Linha 3: "2024";"11";"87088000";"11";"493";"SP";"01";"0817800";418615;60355;470512

Linha 4: "2024";"03";"02071400";"10";"173";"SP";"01";"0817800";94080;94080;237562

Linha 5: "2024";"04";"90303390";"11";"158";"MG";"01";"0817800";10;12;1704

In [14]:
pd.read_csv(df_2024, low_memory=False, sep=';', encoding= 'UTF-8')

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2024,4,94036000,11,245,SP,4,817600,8,425,20423
1,2024,11,87088000,11,493,SP,1,817800,418615,60355,470512
2,2024,3,2071400,10,173,SP,1,817800,94080,94080,237562
3,2024,4,90303390,11,158,MG,1,817800,10,12,1704
4,2024,8,40129090,10,158,SC,4,817700,26,26,950
...,...,...,...,...,...,...,...,...,...,...,...
1603791,2024,5,72044900,10,361,AM,1,717800,164980,164980,44921
1603792,2024,8,4062000,10,845,RS,7,1017701,972,972,10397
1603793,2024,12,84254200,11,589,PR,7,1017503,3,32,239
1603794,2024,4,87021000,11,589,PR,7,1017503,27,494810,8127514
1603795,2024,5,39234000,10,158,SP,7,1017500,0,0,12

In [15]:
df_geral = [df_2022, df_2023, df_2024]
ANTAQ_Int = pd.DataFrame()
for df_geral in df_geral:
    df = pd.read_csv(df_geral, sep = ';')
    ANTAQ_Int = pd.concat([ANTAQ_Int, df], ignore_index=True)
df_geral = pd.DataFrame()
ANTAQ_Int.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4663323 entries, 0 to 4663322
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_NCM      int64
 3   CO_UNID     int64
 4   CO_PAIS     int64
 5   SG_UF_NCM   object
 6   CO_VIA      int64
 7   CO_URF      int64
 8   QT_ESTAT    int64
 9   KG_LIQUIDO  int64
 10  VL_FOB      int64
dtypes: int64(10), object(1)
memory usage: 391.4+ MB

In [16]:
ANTAQ_Int.head(5)

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2022,6,85045000,11,69,MG,4,817600,2,1399,19576
1,2022,4,39219019,10,586,SP,7,917500,3914,3914,12672
2,2022,1,44071100,16,249,SC,1,927800,21945,8409167,5177394
3,2022,11,84672100,11,521,RS,1,817800,10,25,487
4,2022,10,8072000,10,23,RN,4,417901,55356,55356,71511

In [17]:
ANTAQ_Int.tail(5)

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
4663318,2024,5,72044900,10,361,AM,1,717800,164980,164980,44921
4663319,2024,8,4062000,10,845,RS,7,1017701,972,972,10397
4663320,2024,12,84254200,11,589,PR,7,1017503,3,32,239
4663321,2024,4,87021000,11,589,PR,7,1017503,27,494810,8127514
4663322,2024,5,39234000,10,158,SP,7,1017500,0,0,12

In [18]:
df_geral = ANTAQ_Int.to_csv(caminho_out + 'ANTAQ_Int.csv', index=False)

In [19]:
from google.colab import drive
drive.mount('/content/drive')
via = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/VIA.csv'
urf = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/URF.csv'
pais = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/PAIS.csv'
uf = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/UF.csv'
ncm = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/NCM.csv'
geral = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/ANTAQ_Int.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [76]:
with open(via) as arquivo:
    linhas = arquivo.readlines()
    for linha in linhas:
        print(linha.strip())

"CO_VIA";"NO_VIA"
"00";"VIA NAO DECLARADA"
"01";"MARITIMA"
"02";"FLUVIAL"
"03";"LACUSTRE"
"04";"AEREA"
"05";"POSTAL"
"06";"FERROVIARIA"
"07";"RODOVIARIA"
"08";"CONDUTO/REDE DE TRANSMISSAO"
"09";"MEIOS PROPRIOS"
"10";"ENTRADA/SAIDA FICTA"
"99";"VIA DESCONHECIDA"
"13";"POR REBOQUE"
"11";"COURIER"
"15";"VICINAL FRONTEIRICO"
"14";"DUTOS"
"12";"EM MAOS"

In [77]:
mesclado1 = pd.read_csv(via, sep = ';')
mesclado1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO_VIA  17 non-null     int64
 1   NO_VIA  17 non-null     object
dtypes: int64(1), object(1)
memory usage: 404.0+ bytes

In [21]:
mesclado2 = pd.read_csv(geral, sep=',', header=0, names=['CO_ANO', 'CO_MES', 'CO_NCM', 'CO_UNID', 'CO_PAIS', 'SG_UF_NCM', 'CO_VIA', 'CO_URF', 'QT_ESTAT', 'KG_LIQUIDO', 'VL_FOB'])
mesclado2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4663323 entries, 0 to 4663322
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_NCM      int64
 3   CO_UNID     int64
 4   CO_PAIS     int64
 5   SG_UF_NCM   object
 6   CO_VIA      int64
 7   CO_URF      int64
 8   QT_ESTAT    int64
 9   KG_LIQUIDO  int64
 10  VL_FOB      int64
dtypes: int64(10), object(1)
memory usage: 391.4+ MB

In [22]:
mesclado3 = pd.read_csv(urf, sep = ';', encoding='latin-1')
mesclado3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO_URF  278 non-null    int64
 1   NO_URF  278 non-null    object
dtypes: int64(1), object(1)
memory usage: 4.5+ KB

In [23]:
mesclado4 = pd.read_csv(pais, sep = ';', encoding='latin-1')
mesclado4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281 entries, 0 to 280
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CO_PAIS        281 non-null    int64
 1   CO_PAIS_ISON3  281 non-null    int64
 2   CO_PAIS_ISOA3  281 non-null    object
 3   NO_PAIS        281 non-null    object
 4   NO_PAIS_ING    281 non-null    object
 5   NO_PAIS_ESP    281 non-null    object
dtypes: int64(2), object(4)
memory usage: 13.3+ KB

In [24]:
mesclado5 = pd.read_csv(uf, sep = ';', encoding='latin-1')
mesclado5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CO_UF      34 non-null     int64
 1   SG_UF      34 non-null     object
 2   NO_UF      34 non-null     object
 3   NO_REGIAO  34 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.2+ KB

In [25]:
mesclado6 = pd.read_csv(ncm, sep = ';', encoding='latin-1')
mesclado6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13720 entries, 0 to 13719
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CO_NCM          13720 non-null  int64
 1   CO_UNID         13720 non-null  int64
 2   CO_SH6          13720 non-null  int64
 3   CO_PPE          13418 non-null  float64
 4   CO_PPI          13418 non-null  float64
 5   CO_FAT_AGREG    13699 non-null  float64
 6   CO_CUCI_ITEM    13720 non-null  object
 7   CO_CGCE_N3      13720 non-null  int64
 8   CO_SIIT         13418 non-null  float64
 9   CO_ISIC_CLASSE  13720 non-null  int64
 10  CO_EXP_SUBSET   13417 non-null  float64
 11  NO_NCM_POR      13720 non-null  object
 12  NO_NCM_ESP      13720 non-null  object
 13  NO_NCM_ING      13720 non-null  object
dtypes: float64(5), int64(5), object(4)
memory usage: 1.5+ MB

In [26]:
print(mesclado1.columns)
print(mesclado2.columns)
print(mesclado3.columns)
print(mesclado4.columns)
print(mesclado5.columns)
print(mesclado6.columns)

Index(['CO_VIA', 'NO_VIA'], dtype='object')
Index(['CO_ANO', 'CO_MES', 'CO_NCM', 'CO_UNID', 'CO_PAIS', 'SG_UF_NCM',
       'CO_VIA', 'CO_URF', 'QT_ESTAT', 'KG_LIQUIDO', 'VL_FOB'],
      dtype='object')
Index(['CO_URF', 'NO_URF'], dtype='object')
Index(['CO_PAIS', 'CO_PAIS_ISON3', 'CO_PAIS_ISOA3', 'NO_PAIS', 'NO_PAIS_ING',
       'NO_PAIS_ESP'],
      dtype='object')
Index(['CO_UF', 'SG_UF', 'NO_UF', 'NO_REGIAO'], dtype='object')
Index(['CO_NCM', 'CO_UNID', 'CO_SH6', 'CO_PPE', 'CO_PPI', 'CO_FAT_AGREG',
       'CO_CUCI_ITEM', 'CO_CGCE_N3', 'CO_SIIT', 'CO_ISIC_CLASSE',
       'CO_EXP_SUBSET', 'NO_NCM_POR', 'NO_NCM_ESP', 'NO_NCM_ING'],
      dtype='object')

In [40]:
VL_AGREGADO = round(tabela_final['VL_FOB']/tabela_final['KG_LIQUIDO'],2)
tabela_final = tabela_final[tabela_final['VL_AGREGADO'] != 0]
print(VL_AGREGADO)

0              1.67
1              1.75
2             29.67
3            633.67
4              1.30
             ...
4663318       80.14
4663319    55912.29
4663320         inf
4663321    39894.50
4663322        9.87
Length: 4663323, dtype: float64

In [49]:
FREQUENCIA = tabela_final.groupby(['CO_MES', 'NO_NCM_POR']).size().reset_index(name='FREQUENCIA')
print(FREQUENCIA)

       CO_MES                                         NO_NCM_POR  FREQUENCIA
0           1                           1,1,1,2-Tetrafluoroetano          15
1           1                1,3-Butilenoglicol (1,3-butanodiol)           1
2           1                   1-Cianoguanidina (diciandiamida)           1
3           1          1-cloro-2, 3-epoxipropano (epicloridrina)           2
4           1                                          1-mentona           1
...       ...                                                ...         ...
84864      12                                    Óxido niqueloso           1
84865      12             Óxidos de boro e outros ácidos bóricos           1
84866      12                                    Óxidos de cromo           1
84867      12                    Óxidos de titânio, tipo anatase           2
84868      12  Óxidos, hidróxidos e peróxidos de outros metai...          29

[84869 rows x 3 columns]

In [52]:
FREQUENCIA['total_mes'] = FREQUENCIA.groupby('CO_MES')['FREQUENCIA'].transform('sum')
FREQUENCIA['PORCENTAGEM_MES'] = (FREQUENCIA['FREQUENCIA'] / FREQUENCIA['total_mes']) * 100
print(FREQUENCIA)

       CO_MES                                         NO_NCM_POR  FREQUENCIA  \
0           1                           1,1,1,2-Tetrafluoroetano          15
1           1                1,3-Butilenoglicol (1,3-butanodiol)           1
2           1                   1-Cianoguanidina (diciandiamida)           1
3           1          1-cloro-2, 3-epoxipropano (epicloridrina)           2
4           1                                          1-mentona           1
...       ...                                                ...         ...
84864      12                                    Óxido niqueloso           1
84865      12             Óxidos de boro e outros ácidos bóricos           1
84866      12                                    Óxidos de cromo           1
84867      12                    Óxidos de titânio, tipo anatase           2
84868      12  Óxidos, hidróxidos e peróxidos de outros metai...          29

       total_mes  porcentagem_mes  PORCENTAGEM_MES
0         355520         0.004219         0.004219
1         355520         0.000281         0.000281
2         355520         0.000281         0.000281
3         355520         0.000563         0.000563
4         355520         0.000281         0.000281
...          ...              ...              ...
84864     403898         0.000248         0.000248
84865     403898         0.000248         0.000248
84866     403898         0.000248         0.000248
84867     403898         0.000495         0.000495
84868     403898         0.007180         0.007180

[84869 rows x 6 columns]

In [53]:
tabela_final = pd.merge(mesclado1, mesclado2, on='CO_VIA')
tabela_final = pd.merge(tabela_final, mesclado3, on='CO_URF')
tabela_final = pd.merge(tabela_final, mesclado4, on='CO_PAIS')
tabela_final = pd.merge(tabela_final, mesclado5, left_on='SG_UF_NCM', right_on='SG_UF')
tabela_final = pd.merge(tabela_final, mesclado6, on='CO_NCM')
tabela_final['VL_AGREGADO'] = round(tabela_final['VL_FOB']/tabela_final['KG_LIQUIDO'],2)
tabela_final = FREQUENCIA.merge(tabela_final, on=['CO_MES', 'NO_NCM_POR'])
tabela_final = tabela_final[tabela_final['VL_AGREGADO'] != 0]

In [54]:
print(tabela_final.head())

   CO_MES                NO_NCM_POR  FREQUENCIA  total_mes  porcentagem_mes  \
0       1  1,1,1,2-Tetrafluoroetano          15     355520         0.004219
1       1  1,1,1,2-Tetrafluoroetano          15     355520         0.004219
2       1  1,1,1,2-Tetrafluoroetano          15     355520         0.004219
3       1  1,1,1,2-Tetrafluoroetano          15     355520         0.004219
4       1  1,1,1,2-Tetrafluoroetano          15     355520         0.004219

   PORCENTAGEM_MES  CO_VIA    NO_VIA  CO_ANO    CO_NCM  ...  CO_PPI  \
0         0.004219       1  MARITIMA    2022  29033911  ...  3710.0
1         0.004219       1  MARITIMA    2022  29033911  ...  3710.0
2         0.004219       1  MARITIMA    2022  29033911  ...  3710.0
3         0.004219       1  MARITIMA    2022  29033911  ...  3710.0
4         0.004219       1  MARITIMA    2022  29033911  ...  3710.0

   CO_FAT_AGREG CO_CUCI_ITEM  CO_CGCE_N3  CO_SIIT  CO_ISIC_CLASSE  \
0           3.0        51137         240   2000.0            2011
1           3.0        51137         240   2000.0            2011
2           3.0        51137         240   2000.0            2011
3           3.0        51137         240   2000.0            2011
4           3.0        51137         240   2000.0            2011

   CO_EXP_SUBSET                    NO_NCM_ESP                    NO_NCM_ING  \
0         1402.0  1, 1, 1, 2 -tetrafluoroetano  1, 1, 1, 2-tetrafluoroethane
1         1402.0  1, 1, 1, 2 -tetrafluoroetano  1, 1, 1, 2-tetrafluoroethane
2         1402.0  1, 1, 1, 2 -tetrafluoroetano  1, 1, 1, 2-tetrafluoroethane
3         1402.0  1, 1, 1, 2 -tetrafluoroetano  1, 1, 1, 2-tetrafluoroethane
4         1402.0  1, 1, 1, 2 -tetrafluoroetano  1, 1, 1, 2-tetrafluoroethane

  VL_AGREGADO
0       12.57
1       55.00
2        7.29
3       74.00
4      211.86

[5 rows x 40 columns]

In [55]:
print(tabela_final.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4659977 entries, 0 to 4663322
Data columns (total 40 columns):
 #   Column           Dtype
---  ------           -----
 0   CO_MES           int64
 1   NO_NCM_POR       object
 2   FREQUENCIA       int64
 3   total_mes        int64
 4   porcentagem_mes  float64
 5   PORCENTAGEM_MES  float64
 6   CO_VIA           int64
 7   NO_VIA           object
 8   CO_ANO           int64
 9   CO_NCM           int64
 10  CO_UNID_x        int64
 11  CO_PAIS          int64
 12  SG_UF_NCM        object
 13  CO_URF           int64
 14  QT_ESTAT         int64
 15  KG_LIQUIDO       int64
 16  VL_FOB           int64
 17  NO_URF           object
 18  CO_PAIS_ISON3    int64
 19  CO_PAIS_ISOA3    object
 20  NO_PAIS          object
 21  NO_PAIS_ING      object
 22  NO_PAIS_ESP      object
 23  CO_UF            int64
 24  SG_UF            object
 25  NO_UF            object
 26  NO_REGIAO        object
 27  CO_UNID_y        int64
 28  CO_SH6           int64
 29  CO_PPE           float64
 30  CO_PPI           float64
 31  CO_FAT_AGREG     float64
 32  CO_CUCI_ITEM     object
 33  CO_CGCE_N3       int64
 34  CO_SIIT          float64
 35  CO_ISIC_CLASSE   int64
 36  CO_EXP_SUBSET    float64
 37  NO_NCM_ESP       object
 38  NO_NCM_ING       object
 39  VL_AGREGADO      float64
dtypes: float64(8), int64(18), object(14)
memory usage: 1.4+ GB
None

In [56]:
colunas_selecionadas = ['CO_ANO','CO_MES','NO_NCM_POR','NO_UF','NO_URF','NO_VIA','NO_PAIS','KG_LIQUIDO','VL_FOB','VL_AGREGADO','FREQUENCIA','PORCENTAGEM_MES']
tabela_final = tabela_final[colunas_selecionadas]

In [59]:
print(tabela_final.head())

   CO_ANO  CO_MES                NO_NCM_POR              NO_UF  \
0    2022       1  1,1,1,2-Tetrafluoroetano  Rio Grande do Sul
1    2022       1  1,1,1,2-Tetrafluoroetano          São Paulo
2    2022       1  1,1,1,2-Tetrafluoroetano  Rio Grande do Sul
3    2022       1  1,1,1,2-Tetrafluoroetano     Rio de Janeiro
4    2022       1  1,1,1,2-Tetrafluoroetano     Rio de Janeiro

                          NO_URF    NO_VIA   NO_PAIS  KG_LIQUIDO  VL_FOB  \
0  1017700 - PORTO DE RIO GRANDE  MARITIMA    Panamá          14     176
1          0217800 - ALF - BELÉM  MARITIMA     Malta           1      55
2  1017700 - PORTO DE RIO GRANDE  MARITIMA   Bahamas          14     102
3      0817800 - PORTO DE SANTOS  MARITIMA  Portugal           1      74
4      0817800 - PORTO DE SANTOS  MARITIMA    Panamá           7    1483

   VL_AGREGADO  FREQUENCIA  PORCENTAGEM_MES
0        12.57          15         0.004219
1        55.00          15         0.004219
2         7.29          15         0.004219
3        74.00          15         0.004219
4       211.86          15         0.004219

In [ ]:
tabela_final.to_csv('tabela_final.csv', index=False)
caminho_out = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/'
tabela_final.to_csv(caminho_out + 'tabela_final.csv', index=False)

KeyboardInterrupt: