In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
from collections import Counter

In [ ]:
caminho_in = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/'
caminho_out = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df_2019= '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/EXP_2019.csv'
df_2020= '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/EXP_2020.csv'
df_2021= '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/EXP_2021.csv'
df_2022= '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/EXP_2022.csv'
df_2023= '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/EXP_2023.csv'
df_2024= '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/EXP_2024.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_2019 = caminho_in + 'EXP_2019.csv'

In [ ]:
pd.read_csv(df_2019, low_memory=False, sep=';', encoding= 'UTF-8')

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2019,12,70193900,10,97,SP,7,147600,0,0,24
1,2019,12,85444200,10,63,SP,4,817700,99,96,9299
2,2019,12,84099111,11,493,SP,4,817600,2,2,63
3,2019,12,87087090,11,493,SP,4,817700,15,231,908
4,2019,12,32041990,10,586,SC,7,147800,1200,1200,26494
...,...,...,...,...,...,...,...,...,...,...,...
1393169,2019,10,65050019,10,589,SP,4,817700,300,300,861
1393170,2019,10,20059900,10,815,RS,1,927800,40210,40210,29975
1393171,2019,10,40093100,10,161,SP,4,817700,0,0,2
1393172,2019,10,7108000,10,573,ES,1,727600,13,13,46
1393173,2019,10,94036000,11,87,SC,4,817700,10,405,290

In [ ]:
df_2020 = caminho_in + 'EXP_2020.csv'
with open(df_2020, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

Linha 1: "CO_ANO";"CO_MES";"CO_NCM";"CO_UNID";"CO_PAIS";"SG_UF_NCM";"CO_VIA";"CO_URF";"QT_ESTAT";"KG_LIQUIDO";"VL_FOB"

Linha 2: "2020";"01";"39211900";"10";"244";"SP";"04";"0817600";1;1;2

Linha 3: "2020";"03";"48183000";"10";"573";"SC";"01";"0917800";1;1;69

Linha 4: "2020";"01";"85364100";"11";"756";"SP";"01";"0817800";341;12;1668

Linha 5: "2020";"07";"69109000";"11";"586";"SP";"07";"0147800";13;8;686

In [ ]:
pd.read_csv(df_2020, low_memory=False, sep=';', encoding= 'UTF-8')

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2020,1,39211900,10,244,SP,4,817600,1,1,2
1,2020,3,48183000,10,573,SC,1,917800,1,1,69
2,2020,1,85364100,11,756,SP,1,817800,341,12,1668
3,2020,7,69109000,11,586,SP,7,147800,13,8,686
4,2020,6,87089990,10,97,SP,7,147600,5960,5960,49740
...,...,...,...,...,...,...,...,...,...,...,...
1344551,2020,8,85051990,10,169,RS,4,817700,0,0,4
1344552,2020,5,85444900,10,467,MA,1,317903,101,77,293
1344553,2020,2,84825090,11,845,SP,4,817700,100,8,690
1344554,2020,12,22021000,17,351,PR,1,927700,12,12,11
1344555,2020,3,85016400,11,386,SC,1,927700,1,76470,469563

In [ ]:
df_2021 = caminho_in + 'EXP_2021.csv'
with open(df_2021, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

Linha 1: "CO_ANO";"CO_MES";"CO_NCM";"CO_UNID";"CO_PAIS";"SG_UF_NCM";"CO_VIA";"CO_URF";"QT_ESTAT";"KG_LIQUIDO";"VL_FOB"

Linha 2: "2021";"01";"40169990";"10";"361";"SP";"01";"0817800";5353;5353;42235

Linha 3: "2021";"02";"94035000";"11";"317";"RS";"01";"1017700";487;49670;53961

Linha 4: "2021";"11";"35051000";"10";"063";"MG";"07";"1017500";144000;144000;99654

Linha 5: "2021";"04";"61023000";"11";"249";"SP";"04";"0817600";14;5;1087

In [ ]:
pd.read_csv(df_2022, low_memory=False, sep=';', encoding= 'UTF-8')

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2022,6,85045000,11,69,MG,4,817600,2,1399,19576
1,2022,4,39219019,10,586,SP,7,917500,3914,3914,12672
2,2022,1,44071100,16,249,SC,1,927800,21945,8409167,5177394
3,2022,11,84672100,11,521,RS,1,817800,10,25,487
4,2022,10,8072000,10,23,RN,4,417901,55356,55356,71511
...,...,...,...,...,...,...,...,...,...,...,...
1495863,2022,11,32061910,10,845,SP,7,1010252,975,975,5489
1495864,2022,1,12024200,10,434,AM,1,227600,4,4,26
1495865,2022,9,18040000,21,249,BA,1,517800,180,180000,1295568
1495866,2022,8,16010000,10,99,SC,1,927800,1820,1820,1930
1495867,2022,8,64031900,13,69,RJ,4,817700,1,1,68

In [ ]:
df_2022 = caminho_in + 'EXP_2022.csv'
with open(df_2022, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

Linha 1: "CO_ANO";"CO_MES";"CO_NCM";"CO_UNID";"CO_PAIS";"SG_UF_NCM";"CO_VIA";"CO_URF";"QT_ESTAT";"KG_LIQUIDO";"VL_FOB"

Linha 2: "2022";"06";"85045000";"11";"069";"MG";"04";"0817600";2;1399;19576

Linha 3: "2022";"04";"39219019";"10";"586";"SP";"07";"0917500";3914;3914;12672

Linha 4: "2022";"01";"44071100";"16";"249";"SC";"01";"0927800";21945;8409167;5177394

Linha 5: "2022";"11";"84672100";"11";"521";"RS";"01";"0817800";10;25;487

In [ ]:
pd.read_csv(df_2023, low_memory=False, sep=';', encoding= 'UTF-8')

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2023,3,84139190,10,160,RJ,4,817700,107365,5,20
1,2023,12,73182100,10,764,SP,1,817800,0,0,84
2,2023,4,84219999,10,40,RS,4,817600,2,2,758
3,2023,5,85291090,10,63,RJ,7,1017503,1,1,275
4,2023,10,84825010,11,63,MG,7,1017503,2,0,9
...,...,...,...,...,...,...,...,...,...,...,...
1563654,2023,11,64029990,13,337,RS,1,817800,4284,2549,38719
1563655,2023,11,85321000,11,670,RS,4,1017801,24,13,226
1563656,2023,2,20091900,10,586,PR,7,917500,17175,17175,12457
1563657,2023,12,9101100,10,160,MA,1,317903,10,10,30
1563658,2023,5,42029200,11,249,RS,4,817700,2,6,30

In [ ]:
df_2023 = caminho_in + 'EXP_2023.csv'
with open(df_2023, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

Linha 1: "CO_ANO";"CO_MES";"CO_NCM";"CO_UNID";"CO_PAIS";"SG_UF_NCM";"CO_VIA";"CO_URF";"QT_ESTAT";"KG_LIQUIDO";"VL_FOB"

Linha 2: "2023";"03";"84139190";"10";"160";"RJ";"04";"0817700";107365;5;20

Linha 3: "2023";"12";"73182100";"10";"764";"SP";"01";"0817800";0;0;84

Linha 4: "2023";"04";"84219999";"10";"040";"RS";"04";"0817600";2;2;758

Linha 5: "2023";"05";"85291090";"10";"063";"RJ";"07";"1017503";1;1;275

In [ ]:
pd.read_csv(df_2024, low_memory=False, sep=';', encoding= 'UTF-8')

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2024,4,94036000,11,245,SP,4,817600,8,425,20423
1,2024,11,87088000,11,493,SP,1,817800,418615,60355,470512
2,2024,3,2071400,10,173,SP,1,817800,94080,94080,237562
3,2024,4,90303390,11,158,MG,1,817800,10,12,1704
4,2024,8,40129090,10,158,SC,4,817700,26,26,950
...,...,...,...,...,...,...,...,...,...,...,...
1603791,2024,5,72044900,10,361,AM,1,717800,164980,164980,44921
1603792,2024,8,4062000,10,845,RS,7,1017701,972,972,10397
1603793,2024,12,84254200,11,589,PR,7,1017503,3,32,239
1603794,2024,4,87021000,11,589,PR,7,1017503,27,494810,8127514
1603795,2024,5,39234000,10,158,SP,7,1017500,0,0,12

In [ ]:
df_2024 = caminho_in + 'EXP_2024.csv'
with open(df_2024, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

Linha 1: "CO_ANO";"CO_MES";"CO_NCM";"CO_UNID";"CO_PAIS";"SG_UF_NCM";"CO_VIA";"CO_URF";"QT_ESTAT";"KG_LIQUIDO";"VL_FOB"

Linha 2: "2024";"04";"94036000";"11";"245";"SP";"04";"0817600";8;425;20423

Linha 3: "2024";"11";"87088000";"11";"493";"SP";"01";"0817800";418615;60355;470512

Linha 4: "2024";"03";"02071400";"10";"173";"SP";"01";"0817800";94080;94080;237562

Linha 5: "2024";"04";"90303390";"11";"158";"MG";"01";"0817800";10;12;1704

In [ ]:
df_2025 = caminho_in + 'EXP_2025.csv'
with open(df_2025, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

Linha 1: "CO_ANO";"CO_MES";"CO_NCM";"CO_UNID";"CO_PAIS";"SG_UF_NCM";"CO_VIA";"CO_URF";"QT_ESTAT";"KG_LIQUIDO";"VL_FOB"

Linha 2: "2025";"01";"04014021";"10";"580";"PR";"01";"0917800";2;2;23

Linha 3: "2025";"03";"07061000";"10";"476";"RJ";"01";"0717800";477;477;912

Linha 4: "2025";"02";"32061130";"10";"586";"SP";"07";"0917500";73;73;752

Linha 5: "2025";"02";"84825010";"11";"249";"SP";"01";"0817800";58128;11810;225946

In [ ]:
pd.read_csv(df_2025, low_memory=False, sep=';', encoding= 'UTF-8')

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2025,1,4014021,10,580,PR,1,917800,2,2,23
1,2025,3,7061000,10,476,RJ,1,717800,477,477,912
2,2025,2,32061130,10,586,SP,7,917500,73,73,752
3,2025,2,84825010,11,249,SP,1,817800,58128,11810,225946
4,2025,3,85122022,11,158,RS,7,1017500,597,88,5075
...,...,...,...,...,...,...,...,...,...,...,...
391935,2025,2,84099190,10,23,PR,4,817600,2,2,120
391936,2025,2,18010000,21,23,SP,4,817600,0,30,29
391937,2025,3,85165000,11,434,SP,1,817800,4,0,1037
391938,2025,1,73182100,10,493,MG,1,817800,0,0,3
391939,2025,1,20058000,10,183,RS,1,1017700,30,30,30

In [ ]:
df_anos = [df_2019, df_2020, df_2021, df_2022, df_2023, df_2024, df_2025]
COMEX_ANOS = pd.DataFrame()
for df_anos in df_anos:
    df = pd.read_csv(df_anos, sep = ';')
    COMEX_ANOS = pd.concat([COMEX_ANOS, df], ignore_index=True)
df_anos = pd.DataFrame()
COMEX_ANOS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9273288 entries, 0 to 9273287
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_NCM      int64
 3   CO_UNID     int64
 4   CO_PAIS     int64
 5   SG_UF_NCM   object
 6   CO_VIA      int64
 7   CO_URF      int64
 8   QT_ESTAT    int64
 9   KG_LIQUIDO  int64
 10  VL_FOB      int64
dtypes: int64(10), object(1)
memory usage: 778.2+ MB

In [ ]:
COMEX_ANOS.head()

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
0,2019,12,70193900,10,97,SP,7,147600,0,0,24
1,2019,12,85444200,10,63,SP,4,817700,99,96,9299
2,2019,12,84099111,11,493,SP,4,817600,2,2,63
3,2019,12,87087090,11,493,SP,4,817700,15,231,908
4,2019,12,32041990,10,586,SC,7,147800,1200,1200,26494

In [ ]:
COMEX_ANOS.tail()

,CO_ANO,CO_MES,CO_NCM,CO_UNID,CO_PAIS,SG_UF_NCM,CO_VIA,CO_URF,QT_ESTAT,KG_LIQUIDO,VL_FOB
9273283,2025,2,84099190,10,23,PR,4,817600,2,2,120
9273284,2025,2,18010000,21,23,SP,4,817600,0,30,29
9273285,2025,3,85165000,11,434,SP,1,817800,4,0,1037
9273286,2025,1,73182100,10,493,MG,1,817800,0,0,3
9273287,2025,1,20058000,10,183,RS,1,1017700,30,30,30

In [ ]:
df_anos = COMEX_ANOS.to_csv(caminho_out + 'COMEX_ANOS.csv', index=False)

In [ ]:
#CSV AUXILIARES
from google.colab import drive
drive.mount('/content/drive')
via = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/VIA.csv'
urf = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/URF.csv'
pais = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/PAIS.csv'
uf = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/UF.csv'
ncm = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/NCM.csv'
geral = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/COMEX_ANOS.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
mesclado1 = pd.read_csv(via, sep=';', encoding='latin-1')
mesclado1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO_VIA  17 non-null     int64
 1   NO_VIA  17 non-null     object
dtypes: int64(1), object(1)
memory usage: 404.0+ bytes

In [ ]:
mesclado2 = pd.read_csv(geral, sep=',', encoding='UTF-8',low_memory=False)
mesclado2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9273288 entries, 0 to 9273287
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   CO_ANO      int64
 1   CO_MES      int64
 2   CO_NCM      int64
 3   CO_UNID     int64
 4   CO_PAIS     int64
 5   SG_UF_NCM   object
 6   CO_VIA      int64
 7   CO_URF      int64
 8   QT_ESTAT    int64
 9   KG_LIQUIDO  int64
 10  VL_FOB      int64
dtypes: int64(10), object(1)
memory usage: 778.2+ MB

In [ ]:
mesclado3 = pd.read_csv(urf, sep = ';', encoding='latin-1')
mesclado3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CO_URF  278 non-null    int64
 1   NO_URF  278 non-null    object
dtypes: int64(1), object(1)
memory usage: 4.5+ KB

In [ ]:
mesclado4 = pd.read_csv(pais, sep = ';', encoding='latin-1')
mesclado4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281 entries, 0 to 280
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CO_PAIS        281 non-null    int64
 1   CO_PAIS_ISON3  281 non-null    int64
 2   CO_PAIS_ISOA3  281 non-null    object
 3   NO_PAIS        281 non-null    object
 4   NO_PAIS_ING    281 non-null    object
 5   NO_PAIS_ESP    281 non-null    object
dtypes: int64(2), object(4)
memory usage: 13.3+ KB

In [ ]:
mesclado5 = pd.read_csv(uf, sep = ';', encoding='latin-1')
mesclado5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CO_UF      34 non-null     int64
 1   SG_UF      34 non-null     object
 2   NO_UF      34 non-null     object
 3   NO_REGIAO  34 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.2+ KB

In [ ]:
mesclado6 = pd.read_csv(ncm, sep = ';', encoding='latin-1')
mesclado6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13720 entries, 0 to 13719
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CO_NCM          13720 non-null  int64
 1   CO_UNID         13720 non-null  int64
 2   CO_SH6          13720 non-null  int64
 3   CO_PPE          13418 non-null  float64
 4   CO_PPI          13418 non-null  float64
 5   CO_FAT_AGREG    13699 non-null  float64
 6   CO_CUCI_ITEM    13720 non-null  object
 7   CO_CGCE_N3      13720 non-null  int64
 8   CO_SIIT         13418 non-null  float64
 9   CO_ISIC_CLASSE  13720 non-null  int64
 10  CO_EXP_SUBSET   13417 non-null  float64
 11  NO_NCM_POR      13720 non-null  object
 12  NO_NCM_ESP      13720 non-null  object
 13  NO_NCM_ING      13720 non-null  object
dtypes: float64(5), int64(5), object(4)
memory usage: 1.5+ MB

In [ ]:
print(mesclado1.columns)
print(mesclado2.columns)
print(mesclado3.columns)
print(mesclado4.columns)
print(mesclado5.columns)
print(mesclado6.columns)

Index(['CO_VIA', 'NO_VIA'], dtype='object')
Index(['CO_ANO', 'CO_MES', 'CO_NCM', 'CO_UNID', 'CO_PAIS', 'SG_UF_NCM',
       'CO_VIA', 'CO_URF', 'QT_ESTAT', 'KG_LIQUIDO', 'VL_FOB'],
      dtype='object')
Index(['CO_URF', 'NO_URF'], dtype='object')
Index(['CO_PAIS', 'CO_PAIS_ISON3', 'CO_PAIS_ISOA3', 'NO_PAIS', 'NO_PAIS_ING',
       'NO_PAIS_ESP'],
      dtype='object')
Index(['CO_UF', 'SG_UF', 'NO_UF', 'NO_REGIAO'], dtype='object')
Index(['CO_NCM', 'CO_UNID', 'CO_SH6', 'CO_PPE', 'CO_PPI', 'CO_FAT_AGREG',
       'CO_CUCI_ITEM', 'CO_CGCE_N3', 'CO_SIIT', 'CO_ISIC_CLASSE',
       'CO_EXP_SUBSET', 'NO_NCM_POR', 'NO_NCM_ESP', 'NO_NCM_ING'],
      dtype='object')

In [ ]:
TABELA_OFICIAL = pd.merge(mesclado1, mesclado2, on='CO_VIA')
TABELA_OFICIAL = pd.merge(TABELA_OFICIAL, mesclado3, on='CO_URF')
TABELA_OFICIAL = pd.merge(TABELA_OFICIAL, mesclado4, on='CO_PAIS')
TABELA_OFICIAL = pd.merge(TABELA_OFICIAL, mesclado5, left_on='SG_UF_NCM', right_on='SG_UF')
TABELA_OFICIAL = pd.merge(TABELA_OFICIAL, mesclado6, on='CO_NCM')

In [ ]:
# Calcula o valor agregado
TABELA_OFICIAL['VL_AGREGADO'] = round(TABELA_OFICIAL['VL_FOB'] /TABELA_OFICIAL['KG_LIQUIDO'], 2)

# Filtro para valores maiores que 0.001.
TABELA_OFICIAL = TABELA_OFICIAL[
    (TABELA_OFICIAL['VL_FOB'] != 0) &
    (TABELA_OFICIAL['VL_FOB'] > 0.001) &
    (TABELA_OFICIAL['KG_LIQUIDO'] != 0) &
    (TABELA_OFICIAL['KG_LIQUIDO'] > 0.001)]

TABELA_OFICIAL['VL_AGREGADO'] = round(TABELA_OFICIAL['VL_FOB'] / TABELA_OFICIAL['KG_LIQUIDO'], 2)

# Remove VL_AGREGADO = 0
TABELA_OFICIAL = TABELA_OFICIAL[TABELA_OFICIAL['VL_AGREGADO'] != 0]
TABELA_OFICIAL = TABELA_OFICIAL.dropna()
print(TABELA_OFICIAL.head())

   CO_VIA             NO_VIA  CO_ANO  CO_MES    CO_NCM  CO_UNID_x  CO_PAIS  \
0       0  VIA NAO DECLARADA    2019       6  18063110         10      351
1       0  VIA NAO DECLARADA    2019      12   9101100         10      741
2       0  VIA NAO DECLARADA    2019      12   7101000         10      386
3       0  VIA NAO DECLARADA    2019      12   2102000         10      476
4       0  VIA NAO DECLARADA    2019      12   8083000         10      580

  SG_UF_NCM  CO_URF  QT_ESTAT  ...  CO_FAT_AGREG  CO_CUCI_ITEM CO_CGCE_N3  \
0        ES  710400         5  ...           3.0          0733        324
1        MA  320151        22  ...           1.0         07527        323
2        MA  320151       150  ...           1.0         05469        323
3        MA  320151       138  ...           1.0         01681        324
4        MA  320151       103  ...           1.0         05792        323

   CO_SIIT CO_ISIC_CLASSE CO_EXP_SUBSET  \
0   4000.0           1073         205.0
1   9000.0            128        8099.0
2   4000.0           1030        8099.0
3   4000.0           1010         508.0
4   9000.0            113        2399.0

                                          NO_NCM_POR  \
0     Chocolate recheado, em tabletes, barras e paus
1                  Gengibre, não triturado nem em pó
2  Batatas, não cozidas ou cozidas em água ou vap...
3  Carnes de bovinos, salgadas/em salmoura/secas/...
4                                     Pêras, frescas

                                          NO_NCM_ESP  \
0  Chocolate rellenos, en bloques, tabletas y barras
1               Jengibre, sin triturar ni pulverizar
2  Patatas congeladas, aunque estén cocidas en ag...
3  Carnes de la esp.bovina, saladas/en salm./seca...
4                                     Peras, frescas

                                          NO_NCM_ING VL_AGREGADO
0        Filled chocolate, in tablets, slabs or bars       15.00
1               Ginger, neither crushed nor powdered        2.08
2  Potatoes (froz/uncook/cooked by steaming/boili...        1.09
3       Meat of bovine, salted/in brine/dried/smoked        5.37
4                                       Pears, fresh        2.40

[5 rows x 36 columns]

In [ ]:
#Calculo da FREQUÊNCIA em relação a movimentação dos produtos (NCM).
contagem_NCM = TABELA_OFICIAL['NO_NCM_POR'].value_counts()
total_de_ocorrencias_grupo = TABELA_OFICIAL.groupby(['CO_ANO', 'CO_MES', 'NO_NCM_POR']).size().reset_index(name='contagem_NCM_grupo')

contagem_NCM_df = contagem_NCM.reset_index(name='contagem_total_NCM').rename(columns={'index': 'NO_NCM_POR'})

df_merged = pd.merge(total_de_ocorrencias_grupo, contagem_NCM_df, on=['NO_NCM_POR'])

total_ocorrencias_mes_ano = TABELA_OFICIAL.groupby(['CO_ANO', 'CO_MES']).size().reset_index(name='total_ocorrencias_mes_ano')
df_merged = pd.merge(df_merged, total_ocorrencias_mes_ano, on=['CO_ANO', 'CO_MES'])
df_merged['FREQUENCIA'] = round((df_merged['contagem_NCM_grupo'] / df_merged['total_ocorrencias_mes_ano']) * 100, 2)

TABELA_OFICIAL = pd.merge(TABELA_OFICIAL, df_merged[['CO_ANO', 'CO_MES', 'NO_NCM_POR', 'FREQUENCIA']],
                        on=['CO_ANO', 'CO_MES', 'NO_NCM_POR'], how='left')
print(df_merged.head())

   CO_ANO  CO_MES                                         NO_NCM_POR  \
0    2019       1                           1,1,1,2-Tetrafluoroetano
1    2019       1                 2,2'-Oxidietanol (dietilenoglicol)
2    2019       1              2,6-Di-ter-butil-p-cresol e seus sais
3    2019       1  2-(Cicloexilaminotio)benzotiazol (N-cicloexil-...
4    2019       1  2-(Terbutilaminotio)benzotiazol (N-terbutil-be...

   contagem_NCM_grupo  contagem_total_NCM  total_ocorrencias_mes_ano  \
0                   2                 149                      95828
1                   4                 123                      95828
2                   2                 178                      95828
3                   1                  13                      95828
4                   1                  15                      95828

   FREQUENCIA
0         0.0
1         0.0
2         0.0
3         0.0
4         0.0

In [ ]:
VIAS = ['AEREA', 'FERROVIARIA', 'MARITIMA', 'RODOVIARIA']
TABELA_OFICIAL = TABELA_OFICIAL[TABELA_OFICIAL['NO_VIA'].isin(VIAS)]

In [ ]:
print(TABELA_OFICIAL.head())

       CO_VIA    NO_VIA  CO_ANO  CO_MES    CO_NCM  CO_UNID_x  CO_PAIS  \
92987       1  MARITIMA    2019      12  40169300         10      275
92988       1  MARITIMA    2019      11  83012000         10      275
92989       1  MARITIMA    2019      11  18063110         10      434
92990       1  MARITIMA    2019      11  85364100         11      229
92991       1  MARITIMA    2019      11   2071400         10      369

      SG_UF_NCM  CO_URF  QT_ESTAT  ...  CO_CUCI_ITEM  CO_CGCE_N3 CO_SIIT  \
92987        PR  917800         2  ...         62999         240  3000.0
92988        SP  817800        39  ...         69911         240  3000.0
92989        ES  727600        99  ...          0733         324  4000.0
92990        SP  817800         1  ...         77254         270  2000.0
92991        SC  917800    240650  ...         01235         324  4000.0

       CO_ISIC_CLASSE CO_EXP_SUBSET  \
92987            2219        8099.0
92988            2593        8099.0
92989            1073         205.0
92990            2710        1102.0
92991            1010         503.0

                                              NO_NCM_POR  \
92987  Juntas, gaxetas e semelhantes, de borracha vul...
92988  Fechaduras dos tipos utilizados em veículos au...
92989     Chocolate recheado, em tabletes, barras e paus
92990          Relés para uma tensão não superior a 60 V
92991  Pedaços e miudezas, comestíveis de galos/galin...

                                              NO_NCM_ESP  \
92987  Juntas, empaquetaduras, simil.de caucho vulc.s...
92988  Cerraduras de metal común, para vehículos de m...
92989  Chocolate rellenos, en bloques, tabletas y barras
92990                Réles para una tensión <=60 voltios
92991  Trozos y despojos comest.de gallo/gallina, con...

                                              NO_NCM_ING  VL_AGREGADO  \
92987  Gaskets, washers, similars, of vulcan.rubber, ...        51.50
92988           Locks of base metals, for motor vehicles        94.36
92989        Filled chocolate, in tablets, slabs or bars        15.38
92990                      Relays for tension <= 60volts         2.30
92991       Fowls spec.gal.domest.cuts and offal, frozen         1.90

      FREQUENCIA
92987       0.35
92988       0.09
92989       0.08
92990       0.12
92991       0.70

[5 rows x 37 columns]

In [ ]:
print(TABELA_OFICIAL.info())

<class 'pandas.core.frame.DataFrame'>
Index: 8177985 entries, 92987 to 8271485
Data columns (total 37 columns):
 #   Column          Dtype
---  ------          -----
 0   CO_VIA          int64
 1   NO_VIA          object
 2   CO_ANO          int64
 3   CO_MES          int64
 4   CO_NCM          int64
 5   CO_UNID_x       int64
 6   CO_PAIS         int64
 7   SG_UF_NCM       object
 8   CO_URF          int64
 9   QT_ESTAT        int64
 10  KG_LIQUIDO      int64
 11  VL_FOB          int64
 12  NO_URF          object
 13  CO_PAIS_ISON3   int64
 14  CO_PAIS_ISOA3   object
 15  NO_PAIS         object
 16  NO_PAIS_ING     object
 17  NO_PAIS_ESP     object
 18  CO_UF           int64
 19  SG_UF           object
 20  NO_UF           object
 21  NO_REGIAO       object
 22  CO_UNID_y       int64
 23  CO_SH6          int64
 24  CO_PPE          float64
 25  CO_PPI          float64
 26  CO_FAT_AGREG    float64
 27  CO_CUCI_ITEM    object
 28  CO_CGCE_N3      int64
 29  CO_SIIT         float64
 30  CO_ISIC_CLASSE  int64
 31  CO_EXP_SUBSET   float64
 32  NO_NCM_POR      object
 33  NO_NCM_ESP      object
 34  NO_NCM_ING      object
 35  VL_AGREGADO     float64
 36  FREQUENCIA      float64
dtypes: float64(7), int64(16), object(14)
memory usage: 2.3+ GB
None

In [ ]:
colunas_selecionadas = ['CO_ANO','CO_MES','NO_NCM_POR','SG_UF_NCM','NO_UF','NO_URF','NO_VIA','NO_PAIS','VL_AGREGADO','KG_LIQUIDO','VL_FOB','FREQUENCIA']
TABELA_OFICIAL = TABELA_OFICIAL[colunas_selecionadas]

In [ ]:
print(TABELA_OFICIAL.head())

       CO_ANO  CO_MES                                         NO_NCM_POR  \
92987    2019      12  Juntas, gaxetas e semelhantes, de borracha vul...
92988    2019      11  Fechaduras dos tipos utilizados em veículos au...
92989    2019      11     Chocolate recheado, em tabletes, barras e paus
92990    2019      11          Relés para uma tensão não superior a 60 V
92991    2019      11  Pedaços e miudezas, comestíveis de galos/galin...

      SG_UF_NCM           NO_UF                        NO_URF    NO_VIA  \
92987        PR          Paraná  0917800 - PORTO DE PARANAGUA  MARITIMA
92988        SP       São Paulo     0817800 - PORTO DE SANTOS  MARITIMA
92989        ES  Espírito Santo    0727600 - PORTO DE VITORIA  MARITIMA
92990        SP       São Paulo     0817800 - PORTO DE SANTOS  MARITIMA
92991        SC  Santa Catarina  0917800 - PORTO DE PARANAGUA  MARITIMA

       NO_PAIS  VL_AGREGADO  KG_LIQUIDO  VL_FOB  FREQUENCIA
92987   França        51.50           2     103        0.35
92988   França        94.36          39    3680        0.09
92989  Libéria        15.38          13     200        0.08
92990    Benin         2.30          33      76        0.12
92991   Iraque         1.90      240650  456719        0.70

In [ ]:
TABELA_OFICIAL.to_csv('TABELA_OFICIAL.csv', index=False)
caminho_out = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/'
TABELA_OFICIAL.to_csv(caminho_out + 'TABELA_OFICIAL.csv', index=False)

In [ ]:
#CSV COORDENADAS
from google.colab import drive
drive.mount('/content/drive')
coordenadas_uf = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/coordenadas.csv'
coordenadas_urf = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/coordenadas2.csv'
coordenadas_paises = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/coordenadas3.csv'
GERAL = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/TABELA_OFICIAL.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
FILTRO_UF = 'TABELA_OFICIAL' # Substitua pelo nome do seu arquivo CSV
coluna_estado = 'NO_UF' # Substitua pelo nome real da sua coluna de estados

try:
    df = pd.read_csv(FILTRO_UF + '.csv')
    quantidade_por_estado_df = df[coluna_estado].value_counts()

    print(f"\nQuantidade de cada estado no arquivo CSV '{FILTRO_UF}.csv':")
    print(quantidade_por_estado_df)

except FileNotFoundError:
    print(f"Erro: O arquivo CSV '{FILTRO_UF}.csv' não foi encontrado.")
except KeyError:
    print(f"Erro: A coluna '{coluna_estado}' não foi encontrada no arquivo CSV.")
except Exception as e:
    print(f"Ocorreu um erro: {e}")

Quantidade de cada estado no arquivo CSV 'TABELA_OFICIAL.csv':
NO_UF
São Paulo              3195170
Rio Grande do Sul      1051664
Santa Catarina          886190
Paraná                  782575
Rio de Janeiro          477667
Minas Gerais            394244
Espírito Santo          306490
Bahia                   171551
Maranhão                153058
Ceará                   127840
Pará                    119742
Alagoas                  84559
Amazonas                 73209
Goiás                    72510
Pernambuco               62276
Mato Grosso do Sul       44285
Mato Grosso              42339
Roraima                  20253
Rondônia                 18295
Não Declarada            18070
Amapá                    16682
Rio Grande do Norte      16113
Distrito Federal         10706
Paraíba                   9609
Tocantins                 8036
Acre                      5378
Sergipe                   5252
Piauí                     4222
Name: count, dtype: int64

In [ ]:
TABELA_OFICIAL = pd.read_csv(GERAL, sep = ',', encoding='utf-8')
TABELA_OFICIAL.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8177985 entries, 0 to 8177984
Data columns (total 12 columns):
 #   Column       Dtype
---  ------       -----
 0   CO_ANO       int64
 1   CO_MES       int64
 2   NO_NCM_POR   object
 3   SG_UF_NCM    object
 4   NO_UF        object
 5   NO_URF       object
 6   NO_VIA       object
 7   NO_PAIS      object
 8   VL_AGREGADO  float64
 9   KG_LIQUIDO   int64
 10  VL_FOB       int64
 11  FREQUENCIA   float64
dtypes: float64(2), int64(4), object(6)
memory usage: 748.7+ MB

In [ ]:
mesclado8 = pd.read_csv(coordenadas_uf, sep = ',', encoding='utf-8')
mesclado8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   NO_UF    28 non-null     object
 1   LATI_UF  27 non-null     float64
 2   LONG_UF  27 non-null     float64
dtypes: float64(2), object(1)
memory usage: 804.0+ bytes

In [ ]:
mesclado9 = pd.read_csv(coordenadas_urf, sep = ',', encoding='utf-8')
mesclado9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   NO_URF    69 non-null     object
 1   LATI_URF  69 non-null     float64
 2   LONG_URF  69 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.7+ KB

In [ ]:
mesclado10 = pd.read_csv(coordenadas_paises, sep = ',', encoding='utf-8')
mesclado10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   NO_PAIS    247 non-null    object
 1   LATI_PAIS  203 non-null    float64
 2   LONG_PAIS  203 non-null    float64
dtypes: float64(2), object(1)
memory usage: 5.9+ KB

In [ ]:
print(TABELA_OFICIAL.columns)
print(mesclado8.columns)
print(mesclado9.columns)
print(mesclado10.columns)

Index(['CO_ANO', 'CO_MES', 'NO_NCM_POR', 'SG_UF_NCM', 'NO_UF', 'NO_URF',
       'NO_VIA', 'NO_PAIS', 'VL_AGREGADO', 'KG_LIQUIDO', 'VL_FOB',
       'FREQUENCIA'],
      dtype='object')
Index(['NO_UF', 'LATI_UF', 'LONG_UF'], dtype='object')
Index(['NO_URF', 'LATI_URF', 'LONG_URF'], dtype='object')
Index(['NO_PAIS', 'LATI_PAIS', 'LONG_PAIS'], dtype='object')

In [ ]:
# Exemplo de padronização
def padronizar_coluna(df, col):
    if col in df.columns:
        # Converte para string, remove espaços extras, transforma em maiúsculas
        df[col] = df[col].astype(str).str.strip().str.upper()
    return df

TABELA_OFICIAL = padronizar_coluna(TABELA_OFICIAL, 'NO_UF')
TABELA_OFICIAL = padronizar_coluna(TABELA_OFICIAL, 'NO_URF') # Se TABELA_OFICIAL também tiver URF/PAIS
TABELA_OFICIAL = padronizar_coluna(TABELA_OFICIAL, 'NO_PAIS')

mesclado8 = padronizar_coluna(mesclado8, 'NO_UF')
mesclado9 = padronizar_coluna(mesclado9, 'NO_URF')
mesclado10 = padronizar_coluna(mesclado10, 'NO_PAIS')

# Se a coluna de junção em mesclado7 for 'NO_UF' também, padronize mesclado7['NO_UF']

In [ ]:
print("\nVerificação de valores únicos (APÓS PADRONIZAÇÃO):")
print("TABELA_OFICIAL['NO_UF'].unique():", TABELA_OFICIAL['NO_UF'].unique())
print("mesclado8['NO_UF'].unique():", mesclado8['NO_UF'].unique()) # Use mesclado8 instead of coordenadas_uf
print("TABELA_OFICIAL['NO_URF'].unique():", TABELA_OFICIAL['NO_URF'].unique())
print("mesclado9['NO_URF'].unique():", mesclado9['NO_URF'].unique()) # Use mesclado9 instead of coordenadas_urf
print("TABELA_FINAL['NO_PAIS'].unique():", TABELA_OFICIAL['NO_PAIS'].unique())
print("mesclado10['NO_PAIS'].unique():", mesclado10['NO_PAIS'].unique()) # Use mesclado10 instead of coordenadas_paises

Verificação de valores únicos (APÓS PADRONIZAÇÃO):
TABELA_OFICIAL['NO_UF'].unique(): ['PARANÁ' 'SÃO PAULO' 'ESPÍRITO SANTO' 'SANTA CATARINA' 'MATO GROSSO'
 'PARÁ' 'BAHIA' 'MINAS GERAIS' 'RIO GRANDE DO SUL' 'RIO DE JANEIRO'
 'GOIÁS' 'CEARÁ' 'PERNAMBUCO' 'RIO GRANDE DO NORTE' 'MARANHÃO' 'AMAZONAS'
 'MATO GROSSO DO SUL' 'PARAÍBA' 'RONDÔNIA' 'TOCANTINS' 'AMAPÁ' 'SERGIPE'
 'ALAGOAS' 'PIAUÍ' 'DISTRITO FEDERAL' 'ACRE' 'NÃO DECLARADA' 'RORAIMA']
mesclado8['NO_UF'].unique(): ['SANTA CATARINA' 'RIO GRANDE DO SUL' 'SÃO PAULO' 'RIO GRANDE DO NORTE'
 'PARÁ' 'BAHIA' 'MARANHÃO' 'RIO DE JANEIRO' 'ESPÍRITO SANTO' 'PARANÁ'
 'SERGIPE' 'MINAS GERAIS' 'ALAGOAS' 'AMAZONAS' 'RONDÔNIA' 'MATO GROSSO'
 'CEARÁ' 'GOIÁS' 'MATO GROSSO DO SUL' 'NÃO DECLARADA' 'PERNAMBUCO'
 'TOCANTINS' 'AMAPÁ' 'PARAÍBA' 'DISTRITO FEDERAL' 'ACRE' 'PIAUÍ' 'RORAIMA']
TABELA_OFICIAL['NO_URF'].unique(): ['0917800 - PORTO DE PARANAGUA' '0817800 - PORTO DE SANTOS'
 '0727600 - PORTO DE VITORIA' '0217800 - ALF - BELÉM'
 '0717800 - PORTO DE ITAGUAI' '0517800 - ALF - SALVADOR'
 '1017700 - PORTO DE RIO GRANDE' '0927700 - PORTO DE SAO FRANCISCO DO SUL'
 '0717600 - PORTO DO RIO DE JANEIRO' '0927800 - ITAJAI'
 '0812051 - SAO SEBASTIAO' '0210200 - SANTAREM'
 '1017800 - ALF - PORTO ALEGRE' '0417902 - IRF - PORTO DE SUAPE'
 '0317900 - ALF - FORTALEZA' '0320151 - IRF - PORTO DE SÃO LUÍS'
 '0227600 - PORTO DE MANAUS' '0420154 - IRF NATAL'
 '0927502 - IRF - IMBITUBA' '0520100 - ARACAJU' '0240152 - SANTANA'
 '0710200 - NITEROI' '0440151 - MACEIO' '0417900 - ALF - RECIFE'
 '0710400 - CAMPOS DOS GOITACAZES' '0430151 - CABEDELO'
 '0317902 - IRF - PORTO DE PECÉM' '0510552 - ILHEUS'
 '0147600 - ALF - CORUMBÁ'
 '0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO/GUARULHOS'
 '0317903 - IRF SAO LUIS' '0710251 - IRF CAMPOS DOS GOYTACAZES'
 '0510353 - IRF ILHEUS'
 '0717700 - AEROPORTO INTERNACIONAL DO RIO DE JANEIRO'
 '0250100 - PORTO VELHO' '0147852 - ARF - PORTO MURTINHO'
 '0227603 - TABATINGA' '0917500 - ALF - FOZ DO IGUAÇU'
 '0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS'
 '1017801 - IRF - AEROPORTO INTERNACIONAL SALGADO FILHO'
 '0227700 - AEROPORTO EDUARDO GOMES' '0917900 - ALF - CURITIBA'
 '0617700 - ALF - BELO HORIZONTE'
 '0117600 - AEROPORTO INTERNACIONAL DE BRASILIA'
 '0317901 - IRF - AEROPORTO INTERNACIONAL PINTO MARTINS'
 '0417901 - IRF - AEROPORTO INTERNACIONAL DOS GUARARAPES'
 '0517801 - IRF - AEROPORTO INTERNACIONAL DE SALVADOR'
 '0927501 - IRF - AEROPORTO INTERNACIONAL DE FLORIANÓPOLIS'
 '0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM' '0410251 - PETROLINA'
 '0260100 - BOA VISTA' '0812000 - SAO JOSE DOS CAMPOS'
 '0817900 - SAO PAULO' '0147800 - ALF - PONTA PORÃ' '0260151 - PACARAIMA'
 '1010852 - PORTO XAVIER' '0260152 - BONFIM' '1017503 - IRF - SÃO BORJA'
 '1017500 - ALF - URUGUAIANA' '1010252 - JAGUARAO'
 '0250151 - GUAJARA-MIRIM' '1017701 - IRF - CHUÍ'
 '0927900 - ALF - DIONÍSIO CERQUEIRA'
 '1017900 - ALF - SANTANA DO LIVRAMENTO' '0230155 - IRF - EPITACIOLÂNDIA'
 '0147700 - ALF - MUNDO NOVO' '1010851 - PORTO MAUA'
 '0917501 - IRF - GUAÍRA' '0230154 - ASSIS BRASIL'
 '1017502 - IRF - QUARAÍ' '0917502 - IRF - SANTA HELENA'
 '0130151 - CACERES' '1010253 - BAGE' '1017501 - IRF - ITAQUI'
 '0910300 - CASCAVEL' '1010700 - NOVO HAMBURGO'
 '1010351 - IRF SANTANA DO LIVRAMENTO' '1017505 - IRF PORTO XAVIER'
 '1017504 - IRF PORTO MAUA' '0240151 - OIAPOQUE']
mesclado9['NO_URF'].unique(): ['0927800 - ITAJAI' '0817800 - PORTO DE SANTOS'
 '0317900 - ALF - FORTALEZA' '0217800 - ALF - BELÉM'
 '1017700 - PORTO DE RIO GRANDE' '0917800 - PORTO DE PARANAGUA'
 '0517800 - ALF - SALVADOR' '0317903 - IRF SAO LUIS'
 '0927502 - IRF - IMBITUBA' '0717600 - PORTO DO RIO DE JANEIRO'
 '0727600 - PORTO DE VITORIA' '0927700 - PORTO DE SAO FRANCISCO DO SUL'
 '0710251 - IRF CAMPOS DOS GOYTACAZES' '0227600 - PORTO DE MANAUS'
 '0520100 - ARACAJU' '0440151 - MACEIO' '0717800 - PORTO DE ITAGUAI'
 '1017800 - ALF - PORTO ALEGRE' '0417902 - IRF - PORTO DE SUAPE'
 '0210200 - SANTAREM' '0812051 - SAO SEBASTIAO' '0420154 - IRF NATAL'
 '0430151 - CABEDELO' '0240152 - SANTANA' '0417900 - ALF - RECIFE'
 '0510353 - IRF ILHEUS' '0710200 - NITEROI' '0250100 - PORTO VELHO'
 '0147600 - ALF - CORUMBÁ'
 '0717700 - AEROPORTO INTERNACIONAL DO RIO DE JANEIRO'
 '0147852 - ARF - PORTO MURTINHO' '0227603 - TABATINGA'
 '0817600 - AEROPORTO INTERNACIONAL DE SAO PAULO/GUARULHOS'
 '0417901 - IRF - AEROPORTO INTERNACIONAL DOS GUARARAPES'
 '0817700 - AEROPORTO INTERNACIONAL DE VIRACOPOS'
 '0617700 - ALF - BELO HORIZONTE' '0227700 - AEROPORTO EDUARDO GOMES'
 '0917900 - ALF - CURITIBA'
 '1017801 - IRF - AEROPORTO INTERNACIONAL SALGADO FILHO'
 '0517801 - IRF - AEROPORTO INTERNACIONAL DE SALVADOR'
 '0317901 - IRF - AEROPORTO INTERNACIONAL PINTO MARTINS'
 '0117600 - AEROPORTO INTERNACIONAL DE BRASILIA'
 '0217801 - IRF - AEROPORTO INTERNACIONAL DE BELÉM'
 '0927501 - IRF - AEROPORTO INTERNACIONAL DE FLORIANÓPOLIS'
 '0260100 - BOA VISTA' '0917500 - ALF - FOZ DO IGUAÇU'
 '0817900 - SAO PAULO' '0260151 - PACARAIMA' '0260152 - BONFIM'
 '1017701 - IRF - CHUÍ' '1017500 - ALF - URUGUAIANA'
 '1017503 - IRF - SÃO BORJA' '1010351 - IRF SANTANA DO LIVRAMENTO'
 '1017504 - IRF PORTO MAUA' '0230155 - IRF - EPITACIOLÂNDIA'
 '1010253 - BAGE' '1010252 - JAGUARAO' '0147800 - ALF - PONTA PORÃ'
 '0917501 - IRF - GUAÍRA' '0927900 - ALF - DIONÍSIO CERQUEIRA'
 '0230154 - ASSIS BRASIL' '1017505 - IRF PORTO XAVIER'
 '0147700 - ALF - MUNDO NOVO' '0250151 - GUAJARA-MIRIM'
 '1017502 - IRF - QUARAÍ' '0917502 - IRF - SANTA HELENA'
 '0130151 - CACERES' '1017501 - IRF - ITAQUI' '0240151 - OIAPOQUE']
TABELA_FINAL['NO_PAIS'].unique(): ['FRANÇA' 'LIBÉRIA' 'BENIN' 'IRAQUE' 'CHINA' 'FILIPINAS' 'TAILÂNDIA'
 'PANAMÁ' 'REINO UNIDO' 'FINLÂNDIA' 'ESPANHA' 'MALTA' 'MÉXICO'
 'REPÚBLICA DOMINICANA' 'EQUADOR' 'SINGAPURA' 'HONG KONG' 'ESTADOS UNIDOS'
 'MARSHALL, ILHAS' 'BELIZE' 'CHIPRE' 'NORUEGA' 'ITÁLIA' 'BÉLGICA'
 'ARGENTINA' 'CAYMAN, ILHAS' 'CHILE' 'ARÁBIA SAUDITA' 'ALEMANHA' 'MALÁSIA'
 'URUGUAI' 'SUÍÇA' 'PORTUGAL' 'DINAMARCA' 'ÁFRICA DO SUL' 'GRÉCIA'
 'ARMÊNIA' 'COLÔMBIA' 'NICARÁGUA' 'IRLANDA' 'GUATEMALA' 'SUÉCIA' 'GANA'
 'PERU' 'CANADÁ' 'PAÍSES BAIXOS (HOLANDA)' 'JAPÃO' 'TAIWAN (FORMOSA)'
 'OMÃ' 'COSTA RICA' 'ANGOLA' 'SRI LANKA' 'SURINAME' 'NIGÉRIA' 'AUSTRÁLIA'
 'BAHAMAS' 'COVEITE (KUWEIT)' 'ISRAEL' 'NAMÍBIA' 'CURAÇAO' 'GABÃO'
 'VIRGENS, ILHAS (BRITÂNICAS)' 'TANZÂNIA' 'HONDURAS' 'VIETNÃ' 'BARBADOS'
 'GIBRALTAR' 'ÁUSTRIA' 'VENEZUELA' 'KIRIBATI' 'HAITI' 'PORTO RICO'
 'TRINIDAD E TOBAGO' 'INDONÉSIA' 'COREIA DO SUL' 'ÍNDIA' 'EL SALVADOR'
 'POLÔNIA' 'PAQUISTÃO' 'LÍBANO' 'ROMÊNIA' 'ETIÓPIA' 'ARGÉLIA'
 'GUIANA FRANCESA' 'BAREIN' 'CUBA' 'QUÊNIA' 'TURQUIA' 'ARUBA' 'MADAGASCAR'
 'EGITO' 'RÚSSIA' 'ESLOVÊNIA' 'IRÃ' 'JORDÂNIA' 'ESLOVÁQUIA' 'SERRA LEOA'
 'CABO VERDE' 'CATAR' 'MOÇAMBIQUE' 'EMIRADOS ÁRABES UNIDOS' 'GUIANA'
 'IÊMEN' 'PAPUA NOVA GUINÉ' 'ANTÍGUA E BARBUDA' 'MACEDÔNIA' 'AFEGANISTÃO'
 'MALDIVAS' 'NOVA ZELÂNDIA' 'MARROCOS' 'HUNGRIA' 'BURKINA FASO' 'TONGA'
 'CONGO' 'GUINÉ' 'SÍRIA' 'DOMINICA' 'LETÔNIA' 'TIMOR LESTE' 'ILHA DE MAN'
 'CROÁCIA' 'SUDÃO DO SUL' 'CONGO, REPÚBLICA DEMOCRÁTICA' 'BANGLADESH'
 'UCRÂNIA' 'LÍBIA' 'COMORES' 'ALBÂNIA' 'BÓSNIA-HERZEGOVINA' 'TUNÍSIA'
 'NOVA CALEDÔNIA' 'SENEGAL' 'ANGUILLA' 'ISLÂNDIA' 'BULGÁRIA' 'UGANDA'
 'MONTSERRAT' 'GUADALUPE' 'LITUÂNIA' 'GÂMBIA' 'BOLÍVIA'
 'SÃO TOMÉ E PRÍNCIPE' 'CAZAQUISTÃO' 'GUINÉ EQUATORIAL' 'SANTA LÚCIA'
 'COSTA DO MARFIM' 'MAURITÂNIA' 'BERMUDAS' 'MAURÍCIO' 'ESTÔNIA' 'PARAGUAI'
 'JAMAICA' 'SUDÃO' 'SEICHELES' 'BONAIRE, SAINT EUSTATIUS E SABA' 'NÍGER'
 'GRANADA' 'ZIMBÁBUE' 'SÃO BARTOLOMEU' 'NEPAL' 'MARTINICA' 'MAYOTTE'
 'AZERBAIJÃO' 'CAMBOJA' 'TCHECA, REPÚBLICA' 'SÃO VICENTE E GRANADINAS'
 'BELARUS' 'GUINÉ-BISSAU' 'LUXEMBURGO' 'BOTSUANA' 'DJIBUTI' 'GEÓRGIA'
 'CAMARÕES' 'REPÚBLICA CENTRO-AFRICANA' 'PALESTINA' 'MONTENEGRO' 'MACAU'
 'MIANMAR' 'SÉRVIA' 'ANTÁRTICA' 'MOLDÁVIA' 'SINT MAARTEN' 'TOGO'
 'TURCOMENISTÃO' 'REUNIÃO' 'UZBEQUISTÃO' 'MALAVI' 'BRASIL' 'MONGÓLIA'
 'LAOS' 'LIECHTENSTEIN' 'TURCAS E CAICOS, ILHAS' 'TUVALU' 'FIJI' 'VANUATU'
 'FALKLAND (MALVINAS)' 'ZÂMBIA' 'MALI' 'PITCAIRN' 'SAMOA' 'BRUNEI'
 'COREIA DO NORTE' 'SÃO CRISTÓVÃO E NÉVIS' 'SAARA OCIDENTAL' 'CHADE'
 'POLINÉSIA FRANCESA' 'PACÍFICO, ILHAS DO (EUA)' 'SOMÁLIA' 'RUANDA'
 'PALAU' 'SÃO MARTINHO, ILHA DE (PARTE FRANCESA)' 'JERSEY' 'ANDORRA'
 'SAN MARINO' 'SALOMÃO, ILHAS' 'SANTA HELENA'
 'PROVISÃO DE NAVIOS E AERONAVES' 'VIRGENS, ILHAS (AMERICANAS)'
 'WALLIS E FUTUNA, ILHAS' 'SAMOA AMERICANA' 'NAURU' 'NORFOLK, ILHA' 'GUAM'
 'BURUNDI' 'MÔNACO' 'QUIRGUISTÃO' 'ERITREIA' 'SUAZILÂNDIA'
 'CHRISTMAS (NAVIDAD), ILHA' 'MICRONÉSIA' 'FAROE, ILHAS'
 'TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO' 'TERRAS AUSTRAIS FRANCESAS'
 'NIUE' 'MARIANAS DO NORTE, ILHAS' 'COOK, ILHAS' 'TOQUELAU' 'TADJIQUISTÃO'
 'SÃO PEDRO E MIQUELON' 'ALAND, ILHAS' 'VATICANO' 'GROENLÂNDIA' 'BUTÃO'
 'COCOS (KEELING), ILHAS' 'HEARD E ILHAS MCDONALD, ILHA'
 'GEÓRGIA DO SUL E SANDWICH DO SUL, ILHAS' 'SVALBARD E JAN MAYEN'
 'BOUVET, ILHA' 'GUERNSEY' 'LESOTO']
mesclado10['NO_PAIS'].unique(): ['ESTADOS UNIDOS' 'NICARÁGUA' 'PANAMÁ' 'MÉXICO' 'REINO UNIDO' 'MALTA'
 'SINGAPURA' 'TAIWAN (FORMOSA)' 'ARGENTINA' 'MARSHALL, ILHAS' 'BAHAMAS'
 'BENIN' 'ESPANHA' 'PERU' 'BARBADOS' 'HONG KONG' 'CHILE' 'LIBÉRIA'
 'PAÍSES BAIXOS (HOLANDA)' 'ALEMANHA' 'NORUEGA' 'ÍNDIA' 'INDONÉSIA'
 'EL SALVADOR' 'ROMÊNIA' 'SUÉCIA' 'JORDÂNIA' 'COLÔMBIA' 'CHINA' 'REUNIÃO'
 'BAREIN' 'CONGO, REPÚBLICA DEMOCRÁTICA' 'GRÉCIA' 'EQUADOR' 'IRÃ'
 'TURQUIA' 'PORTUGAL' 'ANGOLA' 'COREIA DO SUL' 'JAPÃO' 'CHIPRE'
 'ÁFRICA DO SUL' 'CAYMAN, ILHAS' 'GUIANA' 'REPÚBLICA DOMINICANA'
 'COSTA RICA' 'BÉLGICA' 'SERRA LEOA' 'ITÁLIA' 'LITUÂNIA' 'CANADÁ'
 'PORTO RICO' 'EMIRADOS ÁRABES UNIDOS' 'GUATEMALA' 'QUÊNIA' 'RÚSSIA'
 'TAILÂNDIA' 'HONDURAS' 'FILIPINAS' 'IRLANDA' 'LÍBIA' 'ESLOVÁQUIA' 'SUÍÇA'
 'ANTÍGUA E BARBUDA' 'FRANÇA' 'ISRAEL' 'BANGLADESH' 'MAURÍCIO' 'DINAMARCA'
 'GABÃO' 'AUSTRÁLIA' 'GIBRALTAR' 'BULGÁRIA' 'VENEZUELA' 'MALDIVAS'
 'NOVA ZELÂNDIA' 'ARGÉLIA' 'IRAQUE' 'PAQUISTÃO' 'SINT MAARTEN' 'GANA'
 'SENEGAL' 'CABO VERDE' 'ARÁBIA SAUDITA' 'JAMAICA' 'CUBA' 'POLÔNIA'
 'GRANADA' 'SURINAME' 'NAMÍBIA' 'URUGUAI' 'PAPUA NOVA GUINÉ' 'CATAR'
 'MALÁSIA' 'MARROCOS' 'GUINÉ' 'POLINÉSIA FRANCESA' 'TRINIDAD E TOBAGO'
 'VIETNÃ' 'CROÁCIA' 'TANZÂNIA' 'HAITI' 'BERMUDAS' 'ARUBA'
 'COVEITE (KUWEIT)' 'ALBÂNIA' 'SUDÃO' 'BRASIL' 'CONGO' 'IÊMEN' 'BELIZE'
 'SANTA LÚCIA' 'UCRÂNIA' 'EGITO' 'NOVA CALEDÔNIA' 'LÍBANO'
 'VIRGENS, ILHAS (BRITÂNICAS)' 'ESLOVÊNIA'
 'BONAIRE, SAINT EUSTATIUS E SABA' 'GUINÉ EQUATORIAL' 'COSTA DO MARFIM'
 'ILHA DE MAN' 'CHADE' 'CURAÇAO' 'TUNÍSIA' 'ESTÔNIA' 'MOÇAMBIQUE'
 'CAMARÕES' 'OMÃ' 'SÃO CRISTÓVÃO E NÉVIS' 'CAMBOJA' 'BELARUS' 'MARTINICA'
 'FAROE, ILHAS' 'MONTSERRAT' 'SÃO VICENTE E GRANADINAS' 'BOLÍVIA'
 'MACEDÔNIA' 'SEICHELES' 'CAZAQUISTÃO' 'BOTSUANA' 'PALAU' 'ANDORRA'
 'LUXEMBURGO' 'ZIMBÁBUE' 'TERRAS AUSTRAIS FRANCESAS' 'GÂMBIA' 'VANUATU'
 'COOK, ILHAS' 'GEÓRGIA' 'GUINÉ-BISSAU' 'MONGÓLIA' 'TOGO' 'TIMOR LESTE'
 'FIJI' 'SAMOA' 'LIECHTENSTEIN' 'MOLDÁVIA' 'COCOS (KEELING), ILHAS'
 'PALESTINA' 'UZBEQUISTÃO' 'ÁUSTRIA' 'AZERBAIJÃO' 'MIANMAR'
 'GUIANA FRANCESA' 'TURCAS E CAICOS, ILHAS' 'TCHECA, REPÚBLICA'
 'GUADALUPE' 'SÉRVIA' 'BÓSNIA-HERZEGOVINA' 'HUNGRIA' 'MADAGASCAR'
 'ETIÓPIA' 'MONTENEGRO' 'FALKLAND (MALVINAS)'
 'SÃO MARTINHO, ILHA DE (PARTE FRANCESA)' 'NIGÉRIA'
 'REPÚBLICA CENTRO-AFRICANA' 'MAURITÂNIA' 'SRI LANKA' 'UGANDA' 'LETÔNIA'
 'SOMÁLIA' 'PITCAIRN' 'BURKINA FASO' 'TUVALU' 'PARAGUAI' 'DOMINICA'
 'TONGA' 'TADJIQUISTÃO' 'FINLÂNDIA' 'LAOS' 'ZÂMBIA' 'ISLÂNDIA' 'GUAM'
 'DJIBUTI' 'KIRIBATI' 'MALI' 'ANGUILLA' 'SÃO TOMÉ E PRÍNCIPE' 'NÍGER'
 'MAYOTTE' 'AFEGANISTÃO' 'NIUE' 'QUIRGUISTÃO' 'SAMOA AMERICANA'
 'TURCOMENISTÃO' 'ARMÊNIA' 'PACÍFICO, ILHAS DO (EUA)' 'ALAND, ILHAS'
 'COMORES' 'SALOMÃO, ILHAS' 'VIRGENS, ILHAS (AMERICANAS)' 'SUDÃO DO SUL'
 'BUTÃO' 'BRUNEI' 'RUANDA' 'MÔNACO' 'SÍRIA' 'SAN MARINO' 'SÃO BARTOLOMEU'
 'NORFOLK, ILHA' 'NEPAL' 'MALAVI' 'ERITREIA' 'MICRONÉSIA' 'TOQUELAU'
 'MACAU' 'WALLIS E FUTUNA, ILHAS' 'SAARA OCIDENTAL'
 'HEARD E ILHAS MCDONALD, ILHA' 'GEÓRGIA DO SUL E SANDWICH DO SUL, ILHAS'
 'ANTÁRTICA' 'VATICANO' 'COREIA DO NORTE' 'BURUNDI' 'GROENLÂNDIA'
 'SANTA HELENA' 'JERSEY' 'SUAZILÂNDIA' 'MARIANAS DO NORTE, ILHAS'
 'SVALBARD E JAN MAYEN' 'BOUVET, ILHA' 'LESOTO' 'GUERNSEY'
 'TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO' 'NAURU']

In [ ]:
TABELA_FINAL = TABELA_OFICIAL.copy()

In [ ]:
# Merge with the loaded DataFrames instead of the file path strings
TABELA_FINAL = pd.merge(TABELA_FINAL, mesclado8, on='NO_UF', how='left',
suffixes=('TABELA_OFICIAL', '_COORD_UF'))

# Merge with the loaded DataFrames
TABELA_FINAL = pd.merge(TABELA_FINAL, mesclado9, on='NO_URF', how='left',
suffixes=('_COORD_UF', '_COORD_URF'))

# Merge with the loaded DataFrames
TABELA_FINAL = pd.merge(TABELA_FINAL, mesclado10, on='NO_PAIS', how='left',
suffixes=('_COORD_URF', '_COORD_PAIS'))

In [ ]:
print(TABELA_FINAL.head())

   CO_ANO  CO_MES                                         NO_NCM_POR  \
0    2019      12  Juntas, gaxetas e semelhantes, de borracha vul...
1    2019      11  Fechaduras dos tipos utilizados em veículos au...
2    2019      11     Chocolate recheado, em tabletes, barras e paus
3    2019      11          Relés para uma tensão não superior a 60 V
4    2019      11  Pedaços e miudezas, comestíveis de galos/galin...

  SG_UF_NCM           NO_UF                        NO_URF    NO_VIA  NO_PAIS  \
0        PR          PARANÁ  0917800 - PORTO DE PARANAGUA  MARITIMA   FRANÇA
1        SP       SÃO PAULO     0817800 - PORTO DE SANTOS  MARITIMA   FRANÇA
2        ES  ESPÍRITO SANTO    0727600 - PORTO DE VITORIA  MARITIMA  LIBÉRIA
3        SP       SÃO PAULO     0817800 - PORTO DE SANTOS  MARITIMA    BENIN
4        SC  SANTA CATARINA  0917800 - PORTO DE PARANAGUA  MARITIMA   IRAQUE

   VL_AGREGADO  KG_LIQUIDO  VL_FOB  FREQUENCIA    LATI_UF    LONG_UF  \
0        51.50           2     103        0.35 -24.484219 -51.814887
1        94.36          39    3680        0.09 -23.550651 -46.633382
2        15.38          13     200        0.08 -19.568768 -40.172199
3         2.30          33      76        0.12 -23.550651 -46.633382
4         1.90      240650  456719        0.70 -27.062837 -51.114965

    LATI_URF   LONG_URF  LATI_PAIS  LONG_PAIS
0 -26.408728 -48.749986 -20.538177 -47.400979
1 -32.012195 -52.041835 -20.538177 -47.400979
2 -20.288918 -40.234205 -20.849714 -41.357619
3 -32.012195 -52.041835 -22.979914 -47.170378
4 -26.408728 -48.749986  -8.111868 -35.274618

In [ ]:
print(TABELA_FINAL.tail())

         CO_ANO  CO_MES                                         NO_NCM_POR  \
8177980    2025       2         Caixas de direção para veículos automóveis
8177981    2025       1  Outras misturas de agentes orgânicos de superf...
8177982    2025       2  Outras placas de trocadores (permutadores) de ...
8177983    2025       3  Carrocerias pata "dumpers"/tratores, exceto ro...
8177984    2025       1  Bolsas, mesmo com tiracolo, incluindo as que n...

        SG_UF_NCM         NO_UF                         NO_URF      NO_VIA  \
8177980        MG  MINAS GERAIS        0147600 - ALF - CORUMBÁ  RODOVIARIA
8177981        SP     SÃO PAULO  0917500 - ALF - FOZ DO IGUAÇU  RODOVIARIA
8177982        PR        PARANÁ  0917500 - ALF - FOZ DO IGUAÇU  RODOVIARIA
8177983        PR        PARANÁ      1017503 - IRF - SÃO BORJA  RODOVIARIA
8177984        SP     SÃO PAULO  0917500 - ALF - FOZ DO IGUAÇU  RODOVIARIA

           NO_PAIS  VL_AGREGADO  KG_LIQUIDO   VL_FOB  FREQUENCIA    LATI_UF  \
8177980    BOLÍVIA        33.83           6      203        0.05 -18.526484
8177981  ARGENTINA         0.80        6000     4797        0.03 -23.550651
8177982   PARAGUAI       143.73          15     2156        0.01 -24.484219
8177983  ARGENTINA        21.49       54741  1176616        0.00 -24.484219
8177984   PARAGUAI        65.00           4      260        0.04 -23.550651

           LONG_UF   LATI_URF   LONG_URF  LATI_PAIS  LONG_PAIS
8177980 -44.158865 -18.998719 -57.653986 -15.214274 -40.250924
8177981 -46.633382 -25.521980 -54.575511 -28.668037 -49.338347
8177982 -51.814887 -25.521980 -54.575511 -20.768500 -42.747223
8177983 -51.814887 -28.624998 -56.027975 -28.668037 -49.338347
8177984 -46.633382 -25.521980 -54.575511 -20.768500 -42.747223

In [ ]:
print(TABELA_FINAL.isnull().sum())

CO_ANO              0
CO_MES              0
NO_NCM_POR          0
SG_UF_NCM           0
NO_UF               0
NO_URF              0
NO_VIA              0
NO_PAIS             0
VL_AGREGADO         0
KG_LIQUIDO          0
VL_FOB              0
FREQUENCIA          0
LATI_UF         18070
LONG_UF         18070
LATI_URF        12847
LONG_URF        12847
LATI_PAIS      438094
LONG_PAIS      438094
dtype: int64

In [ ]:
print(TABELA_FINAL.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8177985 entries, 0 to 8177984
Data columns (total 18 columns):
 #   Column       Dtype
---  ------       -----
 0   CO_ANO       int64
 1   CO_MES       int64
 2   NO_NCM_POR   object
 3   SG_UF_NCM    object
 4   NO_UF        object
 5   NO_URF       object
 6   NO_VIA       object
 7   NO_PAIS      object
 8   VL_AGREGADO  float64
 9   KG_LIQUIDO   int64
 10  VL_FOB       int64
 11  FREQUENCIA   float64
 12  LATI_UF      float64
 13  LONG_UF      float64
 14  LATI_URF     float64
 15  LONG_URF     float64
 16  LATI_PAIS    float64
 17  LONG_PAIS    float64
dtypes: float64(8), int64(4), object(6)
memory usage: 1.1+ GB
None

In [ ]:
colunas_selecionadas = ['CO_ANO','CO_MES','NO_NCM_POR','SG_UF_NCM','NO_UF','LATI_UF','LONG_UF','NO_URF','LATI_URF','LONG_URF','NO_VIA','NO_PAIS','LATI_PAIS','LONG_PAIS','VL_AGREGADO','KG_LIQUIDO','VL_FOB','FREQUENCIA']
TABELA_FINAL = TABELA_FINAL[colunas_selecionadas]

In [ ]:
TABELA_FINAL.to_csv('TABELA_FINAL.csv', index=False)
caminho_out = '/content/drive/My Drive/FIEL LOG. - API II/ARQUIVOS BASE/'
TABELA_FINAL.to_csv(caminho_out + 'TABELA_FINAL.csv', index=False)

In [ ]:
FILTRO_UF = 'TABELA_FINAL' # Substitua pelo nome do seu arquivo CSV
coluna_estado = 'NO_UF' # Substitua pelo nome real da sua coluna de estados

try:
    df = pd.read_csv(FILTRO_UF + '.csv')
    quantidade_por_estado_df = df[coluna_estado].value_counts()

    print(f"\nQuantidade de cada estado no arquivo CSV '{FILTRO_UF}.csv':")
    print(quantidade_por_estado_df)

except FileNotFoundError:
    print(f"Erro: O arquivo CSV '{FILTRO_UF}.csv' não foi encontrado.")
except KeyError:
    print(f"Erro: A coluna '{coluna_estado}' não foi encontrada no arquivo CSV.")
except Exception as e:
    print(f"Ocorreu um erro: {e}")